version: "3.9"
services:
  api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mongo:latest
    hostname: interview_mongodb
    environment:
      - MONGO_INITDB_DATABASE=interview_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - scheduler2:/data/db
    ports:
      - "27017:27017"
volumes:
  scheduler2: